variable "iam_role" {}
variable "lambda_sms_api_connector" {}
variable "s3_lambda_bucket" {}
variable "jar_name" {}
variable "tutorial_app_env" {}
variable "tutorial_app" {}
variable "Name" {}
variable "s3_attachment_bucket" {}
variable "outgoing_connector_sms_sqs" {}